CREATE TABLE [dbo].[BooksAuthors]
(
	ID INT CONSTRAINT PK_ID PRIMARY KEY IDENTITY(1,1),
	BookID INT NOT NULL,
	AuthorID INT NOT NULL,
	CONSTRAINT FK_BooksAuthors_Books FOREIGN KEY (BookID) REFERENCES Books(BookID),
	CONSTRAINT FK_BooksAuthors_Authors FOREIGN KEY (AuthorID) REFERENCES Authors(AuthorID),
)
